apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversaoapp
  template:
    metadata: 
      labels:
        app: conversaoapp
    spec: 
      containers:
      - name: site
        image: kakoferrare/conversao-temperatura:v1
        ports:
        - containerPort: 8080
---